# Form implementation generated from reading ui file './HuMMUS_pyqt/pyqt_ui/HuMMUS_PB_Kraken2.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_trimmomatic(object):
    def setupUi(self, trimmomatic):
        trimmomatic.setObjectName("trimmomatic")
        trimmomatic.resize(228, 321)
        self.verticalGroupBox_2 = QtWidgets.QGroupBox(trimmomatic)
        self.verticalGroupBox_2.setGeometry(QtCore.QRect(20, 10, 191, 271))
        self.verticalGroupBox_2.setObjectName("verticalGroupBox_2")
        self.trimmomatic_UM_layout = QtWidgets.QVBoxLayout(self.verticalGroupBox_2)
        self.trimmomatic_UM_layout.setObjectName("trimmomatic_UM_layout")
        self.label_8 = QtWidgets.QLabel(self.verticalGroupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setIndent(5)
        self.label_8.setObjectName("label_8")
        self.trimmomatic_UM_layout.addWidget(self.label_8)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label.setIndent(5)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.PB_kraken2_thread_spb = QtWidgets.QSpinBox(self.verticalGroupBox_2)
        self.PB_kraken2_thread_spb.setProperty("value", 4)
        self.PB_kraken2_thread_spb.setObjectName("PB_kraken2_thread_spb")
        self.horizontalLayout.addWidget(self.PB_kraken2_thread_spb)
        self.trimmomatic_UM_layout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label_3.setIndent(5)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.PB_kraken2_unclass_chk = QtWidgets.QCheckBox(self.verticalGroupBox_2)
        self.PB_kraken2_unclass_chk.setChecked(True)
        self.PB_kraken2_unclass_chk.setObjectName("PB_kraken2_unclass_chk")
        self.horizontalLayout_3.addWidget(self.PB_kraken2_unclass_chk)
        self.trimmomatic_UM_layout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label_4.setIndent(5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.PB_kraken2_class_chk = QtWidgets.QCheckBox(self.verticalGroupBox_2)
        self.PB_kraken2_class_chk.setChecked(True)
        self.PB_kraken2_class_chk.setObjectName("PB_kraken2_class_chk")
        self.horizontalLayout_4.addWidget(self.PB_kraken2_class_chk)
        self.trimmomatic_UM_layout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label_6.setIndent(5)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.PB_kraken2_confidence_dblspb = QtWidgets.QDoubleSpinBox(self.verticalGroupBox_2)
        self.PB_kraken2_confidence_dblspb.setMaximum(1.0)
        self.PB_kraken2_confidence_dblspb.setProperty("value", 0.2)
        self.PB_kraken2_confidence_dblspb.setObjectName("PB_kraken2_confidence_dblspb")
        self.horizontalLayout_6.addWidget(self.PB_kraken2_confidence_dblspb)
        self.trimmomatic_UM_layout.addLayout(self.horizontalLayout_6)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.trimmomatic_UM_layout.addItem(spacerItem4)

        self.retranslateUi(trimmomatic)
        QtCore.QMetaObject.connectSlotsByName(trimmomatic)

    def retranslateUi(self, trimmomatic):
        _translate = QtCore.QCoreApplication.translate
        trimmomatic.setWindowTitle(_translate("trimmomatic", "Form"))
        self.label_8.setText(_translate("trimmomatic", "Kraken2"))
        self.label.setText(_translate("trimmomatic", "Threads"))
        self.label_3.setText(_translate("trimmomatic", "Unclassified"))
        self.PB_kraken2_unclass_chk.setText(_translate("trimmomatic", "Enable"))
        self.label_4.setText(_translate("trimmomatic", "Classified"))
        self.PB_kraken2_class_chk.setText(_translate("trimmomatic", "Enable"))
        self.label_6.setText(_translate("trimmomatic", "Confidence"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    trimmomatic = QtWidgets.QWidget()
    ui = Ui_trimmomatic()
    ui.setupUi(trimmomatic)
    trimmomatic.show()
    sys.exit(app.exec())
