# Form implementation generated from reading ui file '.\HuMMUS_pyqt\pyqt_ui\HuMMUS_PB_Decontamination.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Bowtie2(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 301, 258))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.trimmomatic_UM_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.trimmomatic_UM_layout.setContentsMargins(0, 0, 0, 0)
        self.trimmomatic_UM_layout.setObjectName("bowtie_UM_layout")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setIndent(5)
        self.label_8.setObjectName("label_8")
        self.trimmomatic_UM_layout.addWidget(self.label_8)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setIndent(5)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.PB_Bowtie2_thread_spb = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.PB_Bowtie2_thread_spb.setObjectName("PB_Bowtie2_thread_spb")
        self.horizontalLayout.addWidget(self.PB_Bowtie2_thread_spb)
        self.trimmomatic_UM_layout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setIndent(5)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.PB_Bowtie2_phred_cmb = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.PB_Bowtie2_phred_cmb.setObjectName("PB_Bowtie2_phred_cmb")
        self.PB_Bowtie2_phred_cmb.addItem("")
        self.PB_Bowtie2_phred_cmb.addItem("")
        self.horizontalLayout_2.addWidget(self.PB_Bowtie2_phred_cmb)
        self.trimmomatic_UM_layout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_9.setIndent(5)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.PB_Bowtie2_sensitivity_cbb = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.PB_Bowtie2_sensitivity_cbb.setObjectName("PB_Bowtie2_sensitivity_cbb")
        self.PB_Bowtie2_sensitivity_cbb.addItem("")
        self.PB_Bowtie2_sensitivity_cbb.addItem("")
        self.PB_Bowtie2_sensitivity_cbb.addItem("")
        self.PB_Bowtie2_sensitivity_cbb.addItem("")
        self.horizontalLayout_8.addWidget(self.PB_Bowtie2_sensitivity_cbb)
        self.trimmomatic_UM_layout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setIndent(5)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.PB_Bowtie2_concordant_chk = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.PB_Bowtie2_concordant_chk.setObjectName("PB_Bowtie2_concordant_chk")
        self.horizontalLayout_7.addWidget(self.PB_Bowtie2_concordant_chk)
        self.trimmomatic_UM_layout.addLayout(self.horizontalLayout_7)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        trimmomatic.setWindowTitle(_translate("trimmomatic", "Form"))
        self.label_8.setText(_translate("trimmomatic", "Bowtie2"))
        self.label.setText(_translate("trimmomatic", "Threads"))
        self.label_2.setText(_translate("trimmomatic", "Phred Score"))
        self.PB_Bowtie2_phred_cmb.setItemText(0, _translate("trimmomatic", "Phred33"))
        self.PB_Bowtie2_phred_cmb.setItemText(1, _translate("trimmomatic", "Phred64"))
        self.label_9.setText(_translate("trimmomatic", "Sensitivity"))
        self.PB_Bowtie2_sensitivity_cbb.setCurrentText(_translate("trimmomatic", "Sensitive"))
        self.PB_Bowtie2_sensitivity_cbb.setItemText(0, _translate("trimmomatic", "Sensitive"))
        self.PB_Bowtie2_sensitivity_cbb.setItemText(1, _translate("trimmomatic", "Very Fast"))
        self.PB_Bowtie2_sensitivity_cbb.setItemText(2, _translate("trimmomatic", "Fast"))
        self.PB_Bowtie2_sensitivity_cbb.setItemText(3, _translate("trimmomatic", "Very Sensitive"))
        self.label_7.setText(_translate("trimmomatic", "Concordant Align"))
        self.PB_Bowtie2_concordant_chk.setText(_translate("trimmomatic", "True"))


    def return_widget(self):
        return self.verticalLayoutWidget_2

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    bowtie = Ui_trimmomatic()
    print(type(trimmomatic))
    bowtie.show()
    sys.exit(app.exec())

