# Form implementation generated from reading ui file './HuMMUS_pyqt/pyqt_ui/HuMMUS_MainOpen.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Dialog.resize(800, 477)
        Dialog.setMinimumSize(QtCore.QSize(800, 400))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 2342343))
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 781, 470))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.minimizebtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimizebtn.sizePolicy().hasHeightForWidth())
        self.minimizebtn.setSizePolicy(sizePolicy)
        self.minimizebtn.setMinimumSize(QtCore.QSize(23, 23))
        self.minimizebtn.setMaximumSize(QtCore.QSize(23, 23))
        self.minimizebtn.setObjectName("minimizebtn")
        self.horizontalLayout_2.addWidget(self.minimizebtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.LogoLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LogoLabel.sizePolicy().hasHeightForWidth())
        self.LogoLabel.setSizePolicy(sizePolicy)
        self.LogoLabel.setMinimumSize(QtCore.QSize(775, 390))
        self.LogoLabel.setMaximumSize(QtCore.QSize(12322, 16777215))
        self.LogoLabel.setText("")
        self.LogoLabel.setObjectName("LogoLabel")
        self.verticalLayout.addWidget(self.LogoLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.DarkMode = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.DarkMode.setChecked(False)
        self.DarkMode.setObjectName("DarkMode")
        self.horizontalLayout.addWidget(self.DarkMode)
        self.GoWithHuMMUSBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GoWithHuMMUSBtn.sizePolicy().hasHeightForWidth())
        self.GoWithHuMMUSBtn.setSizePolicy(sizePolicy)
        self.GoWithHuMMUSBtn.setMinimumSize(QtCore.QSize(150, 30))
        self.GoWithHuMMUSBtn.setMaximumSize(QtCore.QSize(150, 30))
        self.GoWithHuMMUSBtn.setBaseSize(QtCore.QSize(15, 0))
        self.GoWithHuMMUSBtn.setText("")
        self.GoWithHuMMUSBtn.setCheckable(False)
        self.GoWithHuMMUSBtn.setObjectName("GoWithHuMMUSBtn")
        self.horizontalLayout.addWidget(self.GoWithHuMMUSBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "HuMMUS v1.0.0"))
        self.minimizebtn.setText(_translate("Dialog", "-"))
        self.DarkMode.setText(_translate("Dialog", "Dark Mode"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
